webserver:
  hostname: "0.0.0.0"
  port: 5004

imageserver:
  crawler_upkeep: 10

logging:
  level: 'WARNING'

crawlers:
  - name: "Pr0gramm"
    weight: 3
    config:
      tags: '! (-text s:400 -oc -nsfw )'
      promoted: True
      
