name: "CheckConfigs"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - 'master'
  schedule:
    # this means: “At 23:42 on Wednesdays.”
    - cron: '42 23 * * 3'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      - name: Setup Python
        # see https://github.com/actions/setup-python
        uses: actions/setup-python@v1
        # with:
        #  python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade --requirement requirements.txt
      - name: check configs
        run: bin/check_configs.sh
